server:
  tomcat:
    uri-encoding: UTF-8
  port: 10005
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:~/Sources/tmp/testdb;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver